### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by atchuthan** [atchuthan/tiny_apps#1]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

# Modules to migrate

- [ ] web_list_view
- [ ] stock_available_immediately_warning
- [ ] account_reports_total
- [ ] sign_in_out_color
- [ ] product_sales_team
- [ ] mrp_bom_test
- [ ] sale_link
- [ ] project_task_reviewer
- [ ] task_description
- [ ] issue_assign_project
- [ ] project_issue_auto_close
- [ ] account_invoice_cancel_button
- [ ] sale_order_active
- [ ] hr_timesheet_autofocus
- [ ] project_timesheet_summary_limit
- [ ] product_sample_category_validation
- [ ] product_vendor_reference
- [ ] stock_force_availability
- [ ] account_reports_bs
- [ ] analytic_show_task
- [ ] user_email_template
- [ ] mail_restrict_partner_selection
- [ ] trigger_onchange
- [ ] mrp_serial_lot_traceability
- [ ] project_issue_reviewer
- [ ] base_xml_updatable
- [ ] project_show_stages
- [ ] mrp_automate_lot_number
- [ ] project_issue_task_link
- [ ] account_invoice_ship_date
- [ ] stock_available_mrp_kit
- [ ] website_slides_document_datas
- [ ] analytic_show_user
- [ ] stock_remove_scrap_button
- [ ] sale_assign_salesperson
- [ ] project_timesheet_task
- [ ] stock_return_location
- [ ] purchase_supplier_products
- [ ] account_move_line_import
- [ ] account_move_line_warning_disable
- [ ] project_issue_create_task
- [ ] partner_unique_email
- [ ] document_gdrive_folder_upload
